### ISSUE TITLE
Window resize skipped on Load Game.

### ISSUE THREAD

**Issue by KitaenSilva** [KitaenSilva/OSFOP-Project-Repo#10]
The window resizing event call is currently only run at the very start of a new game - it will remain active as long as everything is played in one sitting in this state, but if the game is saved, closed, re-opened, and loaded to the savegame, the window resize script is not triggered, and therefore the window remains a tiny-ass piece of trash.

I'd like to find a way for this script to just run automatically on game START rather than as an event call, in this case - however, it would still need to obey changes made in the settings menu.

Will have to look into this later.

**Comment by Telnaior** [comment]
Why does the window resize at all? The size it loaded up as at first seemed fine, and the resized one is too *large* to fit smaller screens.

**Comment by ShadowJonathan** [comment]
~~blame kit~~
