### ISSUE TITLE
Text box errors as well as a small sprite error

### ISSUE THREAD

**Issue by Darkrune-Wakeflame** [KitaenSilva/OSFOP-Project-Repo#16]
While checking out the paper work in line with the chair in the office, it spits out an empty text box at the end. 
![empty text box](https://cloud.githubusercontent.com/assets/26861264/25072618/db4451fe-2298-11e7-8ef0-7856d8ce3566.PNG)

There is also a small text overflow error during the Alula event.

![dialogue error](https://cloud.githubusercontent.com/assets/26861264/25072621/0317119e-2299-11e7-8675-a15d61f92a84.PNG)

And finally once I entered the Glen-like area a small sprite error in the upper right corner of Niko's sprite "box" came into view. It is exceedingly hard to see against the grass texture so I found a part of the cave where its more noticeable. Also put a red box around it to make it slightly easier to notice.
 
![sprite error here](https://cloud.githubusercontent.com/assets/26861264/25072632/6dfcddfe-2299-11e7-9ba2-c7f3b784a435.PNG)
 

Spent a bit of time messing with the jumping while I still have some free time. Since I know the jumping will be relegated to certain spots this MIGHT not be the most major issue. But I'm-a report it anyway

![jumping](https://cloud.githubusercontent.com/assets/26861264/25072811/e27a36aa-229d-11e7-8db0-9770dd71b6f5.PNG)

**Comment by ShadowJonathan** [comment]
About the last one: i am planning to re-do the light-map for niko, since it was a quick scale-down and some things might've come out of bounds

**Comment by KitaenSilva** [comment]
I actually can't see the last one, myself. Might be due to colour, though. x .x

**Comment by Darkrune-Wakeflame** [comment]
Jump button also lets you jump over event tiles with the greatest of ease.

**Comment by KitaenSilva** [comment]
Empty textbox and alula text overflow has been fixed from commit 0f5a4afcb549ab5c92fb8a5d4c5c4b6508a6a9ef

Wall-walking issue fixed in commit fadf8dba6d536967348228b7fe9816206f8fcf52
