### ISSUE TITLE
Hard to tell which choice is highlighted

### ISSUE THREAD

**Issue by Telnaior** [KitaenSilva/OSFOP-Project-Repo#19]
When making a choice between two options (for example, the Entity's first yes/no prompt), there isn't nearly enough contrast to make it clear which option is actually highlighted. Because the selector also wraps around, you're stuck making a guess which one is highlighted.

**Comment by ShadowJonathan** [comment]
should be pretty noticeable now

**Comment by KitaenSilva** [comment]
I don't believe I un-did any changes, but I would argue that it's still very difficult to tell which choice is selected. I'll look into adding an actual cursor soon.
