### ISSUE TITLE
Character texture glitch

### ISSUE THREAD

**Issue by DaimeneX** [KitaenSilva/OSFOP-Project-Repo#20]
![50fe657bbbe149d9819cf6fca3d7a738](https://cloud.githubusercontent.com/assets/27635283/25072750/9a543e68-22d7-11e7-8dbe-a419f2eed0b3.png)
![screenshot_21](https://cloud.githubusercontent.com/assets/27635283/25072751/9de520b0-22d7-11e7-8dd8-a71e1ca41c2e.png)

When walking sideways there is something above Niko on brighter backgrounds.

**Comment by DaimeneX** [comment]
I might get a gif of that or a recording.

**Comment by ShadowJonathan** [comment]
What part are you referring to?

Can you high-light it?

**Comment by DaimeneX** [comment]
![screenshot_22](https://cloud.githubusercontent.com/assets/27635283/25072797/58f613a0-22d8-11e7-991d-35cae1c7ea2d.png)

I have to redownload GIMP... I'll try to highlight the previous pics once I Get it.

**Comment by DaimeneX** [comment]
![screenshot_22](https://cloud.githubusercontent.com/assets/27635283/25072899/7cbcd48e-22da-11e7-9363-200aa355a612.png)

Brightened up.
Clearly you can see two dots above Niko.

**Comment by ShadowJonathan** [comment]
yeah, that'll go to the "lightmap-needs-redo" folder

but thanks
