### ISSUE TITLE
Jumping is dangerous and breaks somethings

### ISSUE THREAD

**Issue by DaimeneX** [KitaenSilva/OSFOP-Project-Repo#22]
![screenshot_23](https://cloud.githubusercontent.com/assets/27635283/25072850/6f078a56-22d9-11e7-9484-c2f3f8abdf25.png)

In the basement. I don't think we should be able to do that.

**Comment by DaimeneX** [comment]
![screenshot_24](https://cloud.githubusercontent.com/assets/27635283/25072862/ab3d87fa-22d9-11e7-860e-0a2f67056b1d.png)

Hey look!
Walking on walls!
IN CAVES
:D 

This is gonna be fun. I literally forsen that I would be walking through walls.

**Comment by DaimeneX** [comment]
![screenshot_25](https://cloud.githubusercontent.com/assets/27635283/25072872/fda13ff0-22d9-11e7-8a0f-0d861114e6b7.png)

**Comment by DaimeneX** [comment]
![screenshot_26](https://cloud.githubusercontent.com/assets/27635283/25072880/305b5bb0-22da-11e7-9785-cd108b4a0f9a.png)
Out of bounds.
Time to explore 2nd cave system.

**Comment by ShadowJonathan** [comment]
This is noted and will be fixed soon
