### ISSUE TITLE
Office-Jumping

### ISSUE THREAD

**Issue by ghost** [KitaenSilva/OSFOP-Project-Repo#24]
![i am stuck](https://cloud.githubusercontent.com/assets/27637313/25073081/c253385c-2321-11e7-970c-e02fa71da1ae.PNG)

I can not jump back to the original platform.

![whelp](https://cloud.githubusercontent.com/assets/27637313/25073091/0fc1fcfe-2322-11e7-90ba-91f5ece99e8b.PNG)

Happens inside of The Office where jumping is required.

**Comment by KitaenSilva** [comment]
This is precisely the kind of stuff I am concerned about with jumping. Thankye for the find, Rune!

**Comment by BluRue1803** [comment]
Green=JumpSpots
Red=Landing Spots
I can also jump from red to red
![show](https://cloud.githubusercontent.com/assets/27725984/25126216/1c3b1cb6-2464-11e7-85c6-9efed2cfa1ab.png)
You can also jump here
![show2](https://cloud.githubusercontent.com/assets/27725984/25126358/9de7c7c8-2464-11e7-833f-ad2f51763a93.png)
