### ISSUE TITLE
Exclamation emote from Proto is misaligned

### ISSUE THREAD

**Issue by KitaenSilva** [KitaenSilva/OSFOP-Project-Repo#27]
When interacting with Proto the first time, an exclamation emote is supposed to appear [ABOVE] Proto, but instead appears ON TOP OF him.

**Comment by ShadowJonathan** [comment]
plus, it needs to be visible, thus on the lightmap layer

**Comment by ShadowJonathan** [comment]
fixed with c8d719bb27729d0c0681ec65c5e3600ddc928a13
