### ISSUE TITLE
Non-existant walkable tile in Office

### ISSUE THREAD

**Issue by HarperPL** [KitaenSilva/OSFOP-Project-Repo#28]
Smol thing found it randomly 
![43](https://cloud.githubusercontent.com/assets/27634264/25073269/5f10dac6-22e3-11e7-9e92-7ef0d8b2b73e.PNG)
dunno if its important or no but still gonna post it here

**Comment by KitaenSilva** [comment]
Woah, what - this definitely needs to be fixed.

It's actually that tiny piece that shows the side of that grate, but it definitely shouldn't be passable. Good find!
