### ISSUE TITLE
Lamplighter out of thin air

### ISSUE THREAD

**Issue by DaimeneX** [KitaenSilva/OSFOP-Project-Repo#31]
![screenshot_36](https://cloud.githubusercontent.com/assets/27635283/25073282/abb455e2-22e3-11e7-8e94-0cb433950e68.png)

So Kit fixed Amenity and turned into Lamplighter.
Uh.... XD

**Comment by ShadowJonathan** [comment]
...wait, what?

**Comment by DaimeneX** [comment]
OKAY THIS IS EVEN BETTER
![screenshot_37](https://cloud.githubusercontent.com/assets/27635283/25073291/c12160dc-22e3-11e7-816f-0eb9c2f4b2a4.png)

I know this stuff is pre-solstice and most likely wont be in main game, but man. Amenity turning into a random girl is priceless.

**Comment by ShadowJonathan** [comment]
**!!!**

**Comment by KitaenSilva** [comment]
Lolol.

Because these events aren't intended to be kept, I didn't go through and change the graphics to the new Kit sprite or Amentity talksprites. o vo;;

**Comment by KitaenSilva** [comment]
Also "fixed" in commit 794b4c4d0a530ca6c494de7645198b5b407ea212 I believe. ((Testing commit linking...))
