### ISSUE TITLE
Small dialogue and text problems

### ISSUE THREAD

**Issue by MarshieMonarch** [KitaenSilva/OSFOP-Project-Repo#32]
![author is comfimed a guy](https://cloud.githubusercontent.com/assets/27639467/25073443/b8e31688-229b-11e7-8e75-145994e9ab7b.png)
Author is confirmed a male in original

![capitalize s plz](https://cloud.githubusercontent.com/assets/27639467/25073445/c0c3d982-229b-11e7-8c2e-67c4765c3e7d.png)
S in OneShot should be capital

![long while](https://cloud.githubusercontent.com/assets/27639467/25073446/c95a79ac-229b-11e7-8f2c-9ce654616e62.png)
"long while" seems a bit off maybe change it to "long time" ?

![never you mind that seems strange to me](https://cloud.githubusercontent.com/assets/27639467/25073447/d2c4eebe-229b-11e7-9411-97d9b839bb0a.png)
"Never you mind that" also seems a bit weird to me.

That's all for now

**Comment by ShadowJonathan** [comment]
same kind of issue as #21

**Comment by KitaenSilva** [comment]
Some of these are probably colloquial phrases, so I'll try to adjust them to seem a little more universal. The author thing will have to be fixed though, and I'm intentionally de-capitalizing the S in OneShot since I'm using it as a name instead of a title.
