### ISSUE TITLE
Small graphical things

### ISSUE THREAD

**Issue by MarshieMonarch** [KitaenSilva/OSFOP-Project-Repo#33]
![another transparent rock](https://cloud.githubusercontent.com/assets/27639467/25073455/1a0d316e-229c-11e7-9780-c4afa83bfa86.png)
![i think they re all like that](https://cloud.githubusercontent.com/assets/27639467/25073457/1a1fd5da-229c-11e7-95f2-372901109945.png)
![the return of ghost niko](https://cloud.githubusercontent.com/assets/27639467/25073456/1a1fb78a-229c-11e7-91f5-5eb70102e09a.png)
![transparent rock](https://cloud.githubusercontent.com/assets/27639467/25073458/1a22ae72-229c-11e7-9193-942b4a07aa6f.png)
Ghost Niko when you're behind things (even with characters)

![little orange line](https://cloud.githubusercontent.com/assets/27639467/25073462/3464f790-229c-11e7-9ee5-bd3b7945aad8.png)
Little orange line when Niko is facing away from you

That's all for now

**Comment by DaimeneX** [comment]
The first ones are noted in https://github.com/KitaenSilva/OSFOP-Project-Repo/issues/6

As for the last one. Its connected probably to the issue I found.

**Comment by ShadowJonathan** [comment]
^
