### ISSUE TITLE
AWESOME LIGHTING YEAH 

### ISSUE THREAD

**Issue by HarperPL** [KitaenSilva/OSFOP-Project-Repo#35]
(sorry for title had to)
So I pressed F12 while looking for a way to make the window bigger and it just restarted put me back into main menu . 
After trying to load a save from the waking point (With the bed and PC) it gave me this error : 
![obraz](https://cloud.githubusercontent.com/assets/27634264/25073526/ec621282-22e8-11e7-81ee-06a66418d6be.png)

**Comment by HarperPL** [comment]
Tried to recreate it . Happend again with the same Error .

**Comment by DaimeneX** [comment]
I can confirm the issue.
I had the same crash before but couldn't make a screenshot.

**Comment by ShadowJonathan** [comment]
could you describe the steps?

**Comment by HarperPL** [comment]
I could try to record it if shadowplay would god damn response but what i did was 
Load a save in the starting room 
Press f12 
Load again a save in the starting room
Profit

**Comment by HarperPL** [comment]
Also it crashes afterwards

**Comment by KitaenSilva** [comment]
Wew lad, this is indeed a major bug. Thank you for the find, Harper~

**Comment by ShadowJonathan** [comment]
`F12` doesnt seem to crash the game anymore, but puts it right back to the title screen
