### ISSUE TITLE
Window Resize adjustments.

### ISSUE THREAD

**Issue by KitaenSilva** [KitaenSilva/OSFOP-Project-Repo#42]
This is not only intended to fix Issue #10, but also improve visibility for all users.

Find a way for window resize script to launch before "ugly pre-title test shit" CG display on game launch.
Find a way to add a settings menu with a window size option and 3 options - small, medium, and large.
Make sure setting is REMEMBERED on startup and shutdown.

**Comment by ShadowJonathan** [comment]
>find a way to launch script before CG display

just put a script call in the middle of nowhere in one of the scripts, after it has been defined, outside of class boxes

**Comment by ShadowJonathan** [comment]
fixed by commit 99f28b040fb0125cfae4c5b29ec08e4caf3b801f
