### ISSUE TITLE
Niko can read from afar.

### ISSUE THREAD

**Issue by JetSetHentaiologist** [KitaenSilva/OSFOP-Project-Repo#45]
![sabreshot001](https://cloud.githubusercontent.com/assets/27693681/25094412/dfa80d9a-234b-11e7-962c-3069067aa704.png)

Niko has really good eyes.

**Comment by KitaenSilva** [comment]
I can't figure out for the life of me how or why this is happening.

I feel like I will have to move the book to another location if I can't get it sorted.

**Comment by ShadowJonathan** [comment]
This is because of RPGmaker's "counter" feature, where you can interact with objects across tiles

And because of kit's request:

<@90967400962347008>
