### ISSUE TITLE
adfsasdfafd ugly font please go awayyyy

### ISSUE THREAD

**Issue by KitaenSilva** [KitaenSilva/OSFOP-Project-Repo#53]
I don't know how to do it or I'd do it right this second before I bother climbing into my bunk but whatever font is applied currently needs to just disappear because holy bad mcbaddington pls do not.

Please use THSpatial if you choose to tackle this problem - I have my reasons for wanting to use this font. It can be found in the asset pool, here:

https://github.com/KitaenSilva/OSFOP-Asset-Pool/blob/master/Extra/THSpatial.ttf

**Comment by ShadowJonathan** [comment]
I'll try to do this
