### ISSUE TITLE
Combining only half-functional.

### ISSUE THREAD

**Issue by KitaenSilva** [KitaenSilva/OSFOP-Project-Repo#54]
When combining items, it is currently only possible to set one output item.

In cases where combining would result in two or more items - such as consuming the branch and alcohol to get a wet branch and an empty bottle - it is not currently possible.

Attempting to adjust the script to allow for two outputs has so far only resulted in single-output recipes being disabled in the process.

**Comment by ShadowJonathan** [comment]
fixed with 44ee7ddc8b24e0eb07fc51394f016c346932106b
