### ISSUE TITLE
More jump issues

### ISSUE THREAD

**Issue by Darkrune-Wakeflame** [KitaenSilva/OSFOP-Project-Repo#56]
The tile that gives you the jump ability does not automatically strip it from you when you walk back onto it. 
This has allowed me to do things like the following. Please note you can only jump onto the brick tiles like this from the top, meaning there are areas where you can get irreversibly stuck. 
![jump man go](https://cloud.githubusercontent.com/assets/26861264/25169179/ad13c1ba-24ab-11e7-9dfe-9194ed181063.PNG)

Also the jump button continues to be [A] For me, instead of space. 

Addendum: Hitting Z while on the title that gives you the jumping ability will revoke it.

**Comment by KitaenSilva** [comment]
Will have to fix!

I could have sworn that walking back onto the tile would revoke the jump ability, so I'll have to double check it.

**Comment by KitaenSilva** [comment]
Semi-fixed!

Can still "super-jump" over the disabler tile, so still needs a bit more fixin'.

**Comment by KitaenSilva** [comment]
aaaaand this issue is now closed, as of b12282ab0f10f1ddbe3a233a3a988b4395547dfe
