### ISSUE TITLE
Need more fade utilities.

### ISSUE THREAD

**Issue by KitaenSilva** [KitaenSilva/OSFOP-Project-Repo#60]
Current usage of the screenfade-out/-in command is great and all, but it could be better.

Right now, fade-out/-in has no settings - it is always black screen.

What if I want a fade-to-white?
What if I want a fade-in to happen much more slowly - or much more quickly?
What if I want _pictures_ to have a transparent fade-in/-out?
What if I want to use a different animation for a transition or fade?

There is a lot I can't do in this regard, at the moment.

**Comment by ShadowJonathan** [comment]
will add script stuff for this, don't worry

**Comment by KitaenSilva** [comment]
Also a non-issue. Moved to Trello as to-do.
