### ISSUE TITLE
Kit's absence! PLEASE READ.

### ISSUE THREAD

**Issue by KitaenSilva** [KitaenSilva/OSFOP-Project-Repo#65]
Due to technical difficulties, I am unable to access Discord.

I can't sign into Discord without verifying from my gmail, and I can't log-in to my gmail without verifying from my phone, and I'm not even sure _that_ will work.

I am starting this issue purely because I have webhooks set up to relay repo changes and updates to a channel in the dev server, and it will alert a couple friends and such of what's up.

Please comment on this issue to communicate with me for now - it might be inconvenient, but for the moment, this is my only option.

**Comment by Drac32Drac** [comment]
I'm sorry to hear about the difficulties.  That programmer that I have mentioned has joined the dev server and I don't know what to do about coordinating with him on the project when he doesn't have channel access.  Also, in your absence, we have decided to ditch Unity for Unreal Engine for a few technical and legal reasons.  I am loathe to make such a change, but it is for the best.

**Comment by KitaenSilva** [comment]
I'm also having a small amount of family-originating troubles that are entirely unnecessary, which are contributing to the current issue.

As for the new programmer, I would need to have access myself before I can give him access - for now, a temporary measure would be to make a group DM for programming needs and just manually link new issues and similar? I don't imagine this being a problem for terribly long, providing I can verify my accounts and such after re-obtaining my mobile devices.

As for switching from Unity, I have no objections - if it can be made to do what we're after, and it works, I see no reason for me to complain. I am curious about these "legal" reasons, however.

**Comment by Drac32Drac** [comment]
The legal issues stem from the mandatory "Made with Unity" splash screen.  It breaks immersion and detracts from the project as a whole.  Were it a normal project I'd be perfectly happy with the splash screen, but in this one it's a deal breaker. To remove it would require purchasing an expensive license.

**Comment by KitaenSilva** [comment]
...isn't it the same for Unreal Engine?

**Comment by Drac32Drac** [comment]
Not at all.  Unreal Engine operates on royalties instead of subscriptions.

**Comment by KitaenSilva** [comment]
Can we not put either splash as part of the credits, or is there a clause stating they _must_ be at the fore of the game?

**Comment by Drac32Drac** [comment]
With Unity, it's part of the ToS that that splash screen must be present on app load.

**Comment by KitaenSilva** [comment]
Well that's annoying as piss.

Anywho, I'm going out or a bit to try and circumvent this issue by locating my mobile devices.

Be back in a while, I hope.

**Comment by Drac32Drac** [comment]
Good luck.

**Comment by KitaenSilva** [comment]
Fixed for now, lel.
